// <auto-generated />
using System;
using BlazorApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250128021952_AddCreatedAtFieldToUser")]
    partial class AddCreatedAtFieldToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp2.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorApp2.Models.Clientes", b =>
                {
                    b.Property<int>("adcu_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADCU_CODE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adcu_code"));

                    b.Property<int>("adbu_code")
                        .HasColumnType("int")
                        .HasColumnName("ADBU_CODE");

                    b.Property<string>("adcu_coordinates")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_COORDINATES");

                    b.Property<DateTime?>("adcu_datecreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADCU_DATECREATED");

                    b.Property<DateTime?>("adcu_dateupdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADCU_DATEUPDATE");

                    b.Property<string>("adcu_direction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_DIRECTION");

                    b.Property<string>("adcu_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_EMAIL");

                    b.Property<bool?>("adcu_estado")
                        .HasColumnType("bit")
                        .HasColumnName("ADCU_ESTADO");

                    b.Property<string>("adcu_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_NAME");

                    b.Property<string>("adcu_nationalid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_NATIONALID");

                    b.Property<string>("adcu_observation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_OBSERVATION");

                    b.Property<string>("adcu_phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADCU_PHONE");

                    b.Property<string>("adus_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADUS_CODE");

                    b.HasKey("adcu_code");

                    b.ToTable("ADMPAY_CUSTOMER");
                });

            modelBuilder.Entity("BlazorApp2.Models.Negocio", b =>
                {
                    b.Property<int>("adbu_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADBU_CODE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adbu_code"));

                    b.Property<string>("adbu_companyname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_COMPANYNAME");

                    b.Property<DateTime?>("adbu_datecreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADBU_DATECREATED");

                    b.Property<DateTime?>("adbu_dateupdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADBU_DATEUPDATE");

                    b.Property<string>("adbu_direction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_DIRECTION");

                    b.Property<string>("adbu_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_EMAIL");

                    b.Property<string>("adbu_logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_LOGO");

                    b.Property<string>("adbu_manager")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_MANAGER");

                    b.Property<string>("adbu_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_NAME");

                    b.Property<string>("adbu_page")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_PAGE");

                    b.Property<string>("adbu_ruc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_RUC");

                    b.Property<string>("adbu_userupdate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADBU_USERUPDATE");

                    b.HasKey("adbu_code");

                    b.ToTable("ADMPAY_BUSINESS");
                });

            modelBuilder.Entity("BlazorApp2.Models.PagoTrx", b =>
                {
                    b.Property<int>("adat_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADAT_CODE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adat_codigo"));

                    b.Property<string>("adat_comprobante")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADAT_COMPROBANTE");

                    b.Property<DateTime?>("adat_datecreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADAT_DATECREATED");

                    b.Property<DateTime?>("adat_dateupdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADAT_DATEUPDATE");

                    b.Property<string>("adat_descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADAT_DESCRIPCION");

                    b.Property<string>("adat_periodopago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADAT_PERIODOPAGO");

                    b.Property<string>("adat_tipopago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADAT_TIPOPAGO");

                    b.Property<decimal?>("adat_valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ADAT_VALOR");

                    b.Property<int>("adbu_codigo")
                        .HasColumnType("int")
                        .HasColumnName("ADBU_CODE");

                    b.Property<int?>("adcu_code")
                        .HasColumnType("int")
                        .HasColumnName("ADCU_CODE");

                    b.Property<string>("adus_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADUS_CODE");

                    b.HasKey("adat_codigo");

                    b.ToTable("ADMPAY_DATAILTRX");
                });

            modelBuilder.Entity("BlazorApp2.Models.ViewerPagoTrx", b =>
                {
                    b.Property<int?>("anio")
                        .HasColumnType("int");

                    b.Property<string>("clienteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comprobante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("trxDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("viewerPagos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorApp2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorApp2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorApp2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
